=== Abejaruco/apuntesasir/Primero/Asignaturas/Marcas/documentos/ejemplos/ejemplo_57/ejemplo.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:simpleType name="tipoCategoria">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="reposteria" />
			<xsd:enumeration value="carne" />
			<xsd:enumeration value="pescado" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="tipoNota">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1"/>
			<xsd:maxInclusive value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="blog">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="articulo" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="referencia" type="xsd:integer"/> 
							<xsd:element name="titulo" type="xsd:string"/> 
							<xsd:element name="fecha" type="xsd:date"/> 
							<xsd:element name="publicado" type="xsd:boolean"/> 
							<xsd:element name="clasificacion" > 
								<xsd:complexType>
									<xsd:attribute name="categoria" type="tipoCategoria" default="reposteria"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="critica">
								<xsd:complexType>
									<xsd:simpleContent>
										<xsd:extension base="xsd:string">
											<xsd:attribute name="nota" type="tipoNota" use="required"/>
										</xsd:extension>
									</xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="autor" minOccurs="1" maxOccurs="1" type="xsd:string"/> 
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Abejaruco/apuntesasir/Primero/Asignaturas/Marcas/documentos/ejemplos/ejemplo_57/ejemplo.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<blog
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ejemplo.xsd">
	<articulo>
		<referencia>123456</referencia>
		<titulo>Pastel Virtual</titulo>
		<fecha>2012-05-26</fecha>
		<publicado>true</publicado>
		<clasificacion categoria="reposteria"/>
		<critica nota="3">muy sosa</critica>
		<autor>Yo</autor>
	</articulo>
	<articulo>
		<referencia>13579</referencia>
		<titulo>Filete Virtual</titulo>
		<fecha>2012-02-29</fecha>
		<publicado>true</publicado>
		<clasificacion categoria="carne"/>
		<critica nota="10">excelente receta</critica>
		<autor>Nai</autor>
	</articulo>
	<articulo>
		<referencia>246810</referencia>
		<titulo>Merluzo</titulo>
		<fecha>2013-12-13</fecha>
		<publicado>false</publicado>
		<clasificacion categoria="pescado"/>
		<critica nota="5">sosa</critica>
		<autor>Alguien</autor>
	</articulo>
	<articulo>
		<referencia>987654</referencia>
		<titulo>Invisible</titulo>
		<fecha>2000-06-25</fecha>
		<publicado>true</publicado>
		<clasificacion/>
		<critica nota="1">No hay nada</critica>
		<autor>Nadie</autor>
	</articulo>
</blog>
