<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<!--
Ejercicio 4 (14/03/2013)  liga de fútbol

Realizar un DTD y XML (incrustado) para representar los resultados de una liga de fútbol.
La información que se quiere almacenar de cada partido es:

el nombre del equipo local
el nombre del equipo visitante
los goles marcados por el equipo local
los goles marcados por el equipo visitante

Incluye  los siguientes resultados dentro del xml:
Athletic de Bilbao: 1  Real Sociedad: 1
Osasuna: 3 - Alavés: 3
Baskonia: 4 - Eibar: 2

Realiza 3 documentos diferentes (xml+dtd) para cada uno de los siguientes casos:
xxxxxun DTD en el que no haya atributos, sino únicamente etiquetas
un DTD en el que los goles sean atributos
un DTD en el toda la información se guarde en forma de atributos
-->
<!DOCTYPE ligaBBV [
<!ELEMENT ligaBBV (jornada+) >
<!ELEMENT jornada (partido+) >
<!ELEMENT partido (equipo+) >
<!ELEMENT equipo (tipo,nombre,goles) >
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT goles (#PCDATA)>
]>
<ligaBBV>
	<jornada>
		<partido>
			<equipo>
				<tipo>Local</tipo>
				<nombre>Athletic de Bilbao</nombre>
				<goles>2</goles>
			</equipo>
			<equipo>
				<tipo>Visitante</tipo>
				<nombre>Real Sociedad</nombre>
				<goles>1</goles>
			</equipo>
		</partido>
		<partido>
			<equipo>
				<tipo>Local</tipo>
				<nombre>Osasuna</nombre>
				<goles>3</goles>
			</equipo>
			<equipo>
				<tipo>Visitante</tipo>
				<nombre>Alavés</nombre>
				<goles>3</goles>
			</equipo>
		</partido>
		<partido>
			<equipo>
				<tipo>Local</tipo>
				<nombre>Baskonia</nombre>
				<goles>4</goles>
			</equipo>
			<equipo>
				<tipo>Visitante</tipo>
				<nombre>Eibar</nombre>
				<goles>2</goles>
			</equipo>
		</partido>
	</jornada>
</ligaBBV>
